import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';

import { App } from '@/app';
import { env } from '@/config/env';

import './index.css';

/**
 * Starts the MSW mock API in the browser when enabled. The worker file is
 * generated by `npm run msw:init` and must exist in /public.
 */
const enableMocking = async () => {
  if (!env.ENABLE_API_MOCKING) return;
  const { worker } = await import('@/testing/mocks/browser');
  return worker.start({ onUnhandledRequest: 'bypass' });
};

const rootElement = document.getElementById('root');
if (!rootElement) {
  throw new Error('Root element #root not found in index.html');
}

void enableMocking().then(() => {
  createRoot(rootElement).render(
    <StrictMode>
      <App />
    </StrictMode>,
  );
});
